services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: 3.2.2
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}" # 環境変数から取得
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/rails_production"
    volumes:
      - ./log:/rails/log
      - ./storage:/rails/storage
    ports:
      - "80:80"
    depends_on:
      - db
    entrypoint: ["/rails/bin/docker-entrypoint"]
    command: ["./bin/thrust", "./bin/rails", "server"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: